HubSpot/general-store

bower.json, package.json, src/__tests__/GeneralStore-integration-test.js, src/dependencies/StoreDependencyMixin.js
Adds an invariant that checks if another `StoreDependencyMixin` has already been initialized on the component. Currently that wouldn't work but it wouldn't work silently and end up throwing in `componentWillUnmount`.
Also initializes the mixin in `getInitialState` to maintain backwards compatibility and get state key conflict errors.
=> throw if more than one mixin is detected + initialize in getInitialState

bower.json, package.json, src/dependencies/DependencyMap.js, src/dependencies/StoreDependencyMixin.js, src/dependencies/__tests__/DependencyMap-test.js, src/dependencies/connect.js
Because `timesAHundredMinusState` never actually used `state`, it was unnoticed that `state` would be `undefined` when the `deref` was called from `componentWillReceiveProps`. This change should pass the current `state` through at the time of `componentWillReceiveProps` and update the tests to reflect that case.
It looks like the Change log wasnt updated for v1, so I also didn't add anything for this fix. If there is anything else that I missed, let me know.
/cc @colbyr
=> Fix undefined state on prop change

CHANGELOG.md, bower.json, package.json, src/store/StoreFactory.js, src/store/__tests__/StoreFactory-test.js
Allows redefinition of `definiteGetInitialState` which is seriously useful in unit tests.
Instead of having to dispatch a bunch of actions to get to the starting state you want, you can update the factory to jump right to it.
=> Redefine getinitialstate

CHANGELOG.md, README.md, bower.json, package.json, src/GeneralStore.js, src/dependencies/DependencyMap.js, src/dependencies/__tests__/DependencyMap-test.js, src/dependencies/__tests__/StoreDependencyMixin-test.js, src/dependencies/__tests__/connect-test.js, src/store/InspectStore.js, src/store/Store.js, src/store/StoreFactory.js, src/store/__tests__/InspectStore-test.js, src/store/__tests__/Store-test.js, src/store/__tests__/StoreFactory-test.js
Adds an `InspectStore` module for accessing internal store state like state and raw action responses in tests.
Adds a `defineName` to assist in identifying store instances.
=> InspectStore and Store names

CHANGELOG.md, bower.json, package.json, src/dependencies/__tests__/connect-test.js, src/dependencies/connect.js
Adds two statics to the component created by `connect`. 
`dependencies` is a reference to the DependencyMap passed to connect.
`WrappedComponent` is a reference to the BaseComponent passed to connect.
Hopefully this'll make testing connected components easier.
One might render the wrapped component independently of the connect:
```jsx
<ConnectedComponent.WrappedComponent />
```
or test a component's dependencies independently of the component...
```
ConnectedComponent.dependencies[field].deref({});
```
**TODOs**
=> ConnectedComponent has statics to dependencies and WrappedComponent

CHANGELOG.md, bower.json, package.json, src/dependencies/__tests__/connect-test.js, src/dependencies/connect.js
Adds a focus method to `ConnectedComponent` when the `BaseComponent` has a focus method on its prototype.
This could probably be made more generic if it turns out there are other methods we want to call through to.
**TODOs**
=> ConnectedComponent.focus

CHANGELOG.md, bower.json, package.json, src/GeneralStore.js, src/dependencies/BuildComponent.js, src/dependencies/__tests__/BuildComponent-test.js, src/dependencies/__tests__/connectWithState-test.js, src/dependencies/connect.js, src/dependencies/connectWithState.js
`connectWithState` aims to fill the remaining use case for `StoreDependencyMixin` (i.e. dependencies that are resolved with state).
```js
const initialState = {
postId: 1,
};
const dependencies = {
post: {
stores: [PostStore],
deref({state}) {
return PostStore.get(state.postId);
}
}
};
function ShowPost({post, setState, state}) {
return (
<div>
{post.description}
<button onClick={() => setState({postId: state.postId + 1})}>
Next post
</button>
</div>
);
}
export default connectWithState(initialState, dependencies)(ShowPost);
```
**TODOs**
=> connectWithState

CHANGELOG.md, bower.json, package.json, src/dependencies/BuildComponent.js, src/dependencies/__tests__/BuildComponent-test.js
Sometimes when using general-store you see components named "Connected(undefined)" when you'd expect "Connected(MyRealComponentName)". general-store does the right thing React createClass-style components which expose a `displayName` prop, but not for plain javascript functions and classes. Those things expose [`Function.name`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name). I think that making this change will fix that. 
I'm opening this PR as a reminder for myself, if it sounds good then I can add unit tests and a changelog line.
**TODOs**
=> fix displayName of connected components

CHANGELOG.md, README.md, bower.json, package.json, src/store/Store.js
@colbyr @marcneuwirth @theopak 
This allows us to connect to the usual Redux chrome extension using its API. Thoughts on this approach? 
Hooking into one of our stores 
"Diff" view
"State" view (You can see the state at each action)
Each store would have its own instance in the dropdown letting you dive into each store individually. 
The "dispatcher" view is my little way of seeing all dispatches going through but may not be acted on. That code would live inside the app. 
**TODOs**
=> Allow general-store to connect to redux chrome extension

CHANGELOG.md, bower.json, package.json, src/store/Store.js
Thanks to @zsobin for pointing this out. 
@colbyr 
**TODOs**
=> Use unsubscribe method instead of disconnect

CHANGELOG.md, bower.json, package.json, src/store/StoreSingleton.js, src/store/__tests__/StoreSingleton-test.js
=> support defineName on GeneralStore.define() stores

CHANGELOG.md, bower.json, flow-typed/hoist-non-react-statics.js, package.json, src/dependencies/BuildComponent.js, src/dependencies/__tests__/BuildComponent-test.js, src/dependencies/connect.js, src/dependencies/connectWithState.js, yarn.lock
This change is to use `hoist-non-react-statics` to fix code that was causing a warning with React 16.
> `Warning: Connected(...).childContextTypes is specified bu there is no getChildContext() method on the instance. You can either define getChildContext() on Connected(...) or remove childContextTypes from it.`
@Friss 
**TODOs**
=> use hoist-non-react-statics

CHANGELOG.md, package.json, rollup.config.js
This should help prevent `hoist-non-react-statics` and `react-is` from being bundled multiple times in  apps.
=> externalize hoist-non-react-statics from rollup bundle

CHANGELOG.md, package.json, src/dependencies/__tests__/connect-test.js, src/dependencies/connect.tsx
@colbyr @aem @henryqdineen 
Resolves the warnings about not using the `UNSAFE_` prefix methods. Shouldn't be an issue to move over to this now that React >= 16.8 is a peerDep. 
(I wanted to silence this warning in a personal project but will work for us at HubSpot as well)
**TODOs**
=> Use unsafe prefix method names'

CHANGELOG.md, package.json, src/dependencies/__tests__/useStoreDependency-test.js, src/dependencies/useStoreDependency.ts, src/utils/ObjectUtils.ts, src/utils/__tests__/ObjectUtils-test.js, yarn.lock
fixes #74 
By using `shallowCompare` to test dependency changes, and having that function special-case immutable objects rather than just using strict equality, we can ensure that dependency values with nested immutable objects don't trigger infinite re-renders of the component they're in. 
This will be a minor performance regression for single-depth, primitive-only immutable objects by adding a function call to the stack, but will be a performance enhancement for most other cases by preventing unnecessary re-renders when non-primitive values are unchanged in value, even if they change in identity.
Chose to version this as 3.2.0 as there's a notable functionality change by moving to `shallowCompare` rather than `===`
**TODOs**
@ditkin @colbyr
=> fix(useStoreDependency): use shallowCompare to compare results

CHANGELOG.md, package.json, src/utils/ObjectUtils.ts, src/utils/__tests__/ObjectUtils-test.js
Previously, if the first value in a useStoreDependency call was immutable and the second was undefined or null, our checks would blow up. This tests to verify that the objects both exist before checking their members.
The test case fails without the provided patch.
**TODOs**
=> fix(ObjectUtils): only check for hashCode on truthy objects

README.md
Followup from #83 - adds import examples to docs now that we're shipping an ESM entry rather than CJS
=> Update docs to reflect ESM

src/dependencies/__tests__/useStoreDependency-test.js, src/utils/ObjectUtils.ts, src/utils/__tests__/ObjectUtils-test.js
Just a reapplication of the performance fix to `shallowEqual` from #84 onto v3. Will be published as `3.2.2`. See that PR for more information.
=> reapply perf fix from #84 to v3 branch

src/utils/ObjectUtils.ts, src/utils/__tests__/ObjectUtils-test.js
If one of the top-level values in the returned object is an array, `shallowCompare` would always return `false` which would cause `connect` to spin in an infinite loop because deps were always different which means it would infinitely try to re-set the internal dependency value. By adding an explicit shallow comparison for arrays we can bypass this. Theoretically it could still be an issue if a dependency is rebuilding objects with new identities each `deref` and putting them into arrays, but that feels like behavior we should discourage since it'll break lots of other things like React's prop identity checking.
**TODOs**
=> fix shallowCompare for arrays

src/dependencies/__tests__/connect-test.js, src/utils/ObjectUtils.ts, src/utils/__tests__/ObjectUtils-test.js
Ran into another error case with arrays, so I made the decision to compare array values one level deeper. Otherwise, stores that return arrays of objects are very likely to get into an infinite loop. I left a comment explaining the new behavior and why we're not running a strictly shallow equality check
=> fix(shallowCompare): compare objects nested in arrays

src/dependencies/__tests__/connect-test.js, src/dependencies/connect.tsx, src/dependencies/useStoreDependency.ts, src/utils/ObjectUtils.ts, src/utils/__tests__/ObjectUtils-test.js
Hopefully this is the last fix for object equality tests. @benbriggs pointed me to a problem in the Prospects app, as well as a couple other infinite loop cases that I noticed in the rest of the apps I attempted to upgrade.
It turns out that `React.useState` and `React.Component.prototype.setState` use two different equality algorithms! `useState` checks equality using an `Object.is` equivalent, but `setState` uses a deeper diffing algorithm. This means that `useState` will almost always fail to properly diff objects where `setState` was able to parse them just fine. To combat this, we'll instead run our shallowEqual comparison on each value in the state object rather than just the state object as a whole. This, as far as I can tell (React's codebase is incredibly hard to navigate), is …
=> compare values rather than the entire state object

src/dependencies/__tests__/useStoreDependency-test.js, src/dependencies/useStoreDependency.ts
Fixes an issue where `useStoreDependency` would return an incorrect
intermediate value when a prop change causes the dependency value to
change.
Now the updated value is returned immediately when the dependency value
changes, rather than being set in state but not returned until the next
render cycle.
The render cycle for a prop change looked like this:
1. component renders: `useStoreDependency` calculates the value, stores it in initial state, and returns it
2. prop change causes component to re-render: `useStoreDependency` calculates new value; if the value changed from (1): stores the new value in state, __but returns the old cached value from (1)__.
3. internal setState call causes component to re-render: `useStoreDependency` calculates new value, but the value doesn't change (props …
=> Fixes bad intermediate return values from `useStoreDependency`

src/dependencies/__tests__/useStoreDependency-test.js, src/dependencies/useStoreDependency.ts
cc @aem - another possible approach to https://github.com/HubSpot/general-store/pull/95
Avoids duplicate deref calculations in `useStoreDependency`. Only calculate the value once; use it to initialize state (if needed) and as the new value.
When the value changes, two deref calculations will still run:
1. initial render/hook call
2. re-render/hook call triggered by setting the new value in state
**TODOs**
=> avoids duplicate deref calculations in `useStoreDependency`
